force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <label>Incident</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Actual_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_date__c</fullName>
    <label>Actual Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Applies_To__c.field-meta.xml
<CustomField>
    <fullName>Applies_To__c</fullName>
    <label>Applies To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HR System</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Incident__c.field-meta.xml
<CustomField>
    <fullName>Incident__c</fullName>
    <label>Incident #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Planned_End_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_date__c</fullName>
    <label>Planned End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Planned_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_date__c</fullName>
    <label>Planned Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Incidents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reported</fullName>
                <default>true</default>
                <label>Reported</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Analysis In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Business User Clarification</fullName>
            </value>
            <value>
                <fullName>Pending with Third Party</fullName>
            </value>
            <value>
                <fullName>Implementation In Progress</fullName>
            </value>
            <value>
                <fullName>Coding Complete / System Testing</fullName>
            </value>
            <value>
                <fullName>Pending User Confirmation</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/incidentmanagement.cls
public with sharing class incidentmanagement {
    public Incident__c incident { get; set; }
    public Incident__c incSearch { get; set; }
    public List<Incident__c> incSearchResult { get; set; }

    public incidentmanagement(ApexPages.StandardController controller) {
        incSearch = new Incident__c();
    }

    public void searchIncidents() {
        incSearchResult = [
            SELECT Incident__c, Status__c, Applies_to__c, Summary__c
            FROM Incident__c
            WHERE
                Status__c = :incSearch.Status__c
                OR Applies_To__c = :incSearch.Applies_To__c
        ];
    }

    public void queryIncident() {
        try {
            Id incId = System.currentPageReference()
                .getParameters()
                .get('incid');
            incident = [
                SELECT
                    Incident__c,
                    Summary__c,
                    Responsible__c,
                    Priority__c,
                    Id,
                    Planned_Start_date__c,
                    Planned_End_date__c,
                    Actual_Start_date__c,
                    Actual_End_date__c,
                    Status__c,
                    Remarks__c
                FROM Incident__c
                WHERE id = :incId
            ];
        } catch (exception e) {
            System.debug(e);
        }
    }

    public void saveinc() {
        try {
            update incident;
        } catch (Exception e) {
            System.debug(e);
        }
    }

    // LWC Methods go here
    @AuraEnabled(cacheable=true)
    public static List<Incident__c> searchIncidentsLWC(
        String status,
        String appliesTo
    ) {
        try {
            return [
                SELECT Incident__c, Status__c, Applies_to__c, Summary__c
                FROM Incident__c
                WHERE Status__c = :status OR Applies_To__c = :appliesTo
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}